# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # repository root
    schedule:
      interval: "daily"
    labels: ["dependencies"]
    commit-message:
      prefix: "build(prod):"
      prefix-development: "build(dev):"

  - package-ecosystem: "github-actions"
    directory: "/" # `.github/workflows`
    schedule:
      interval: "daily"
    labels: ["dependencies"]
    commit-message:
      prefix: "ci:"
