default_stages: [commit]

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
