default_stages: [commit]

repos:
  - repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

  - repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]

  - repo: local
    hooks:
    -   id: commitizen
        name: commitizen
        entry: commitizen
        language: system
        stages: [commit-msg]

  - repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

  - repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
