"""Initial generation.

Revision ID: 4fbd0213f158
Revises:
Create Date: 2021-06-13 20:52:24.739338

"""
import sqlalchemy as sa

import moe
from alembic import op

# revision identifiers, used by Alembic.
revision = "4fbd0213f158"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("path", moe.core.library.lib_item.PathType(), nullable=False),
        sa.PrimaryKeyConstraint("artist", "title", "year"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "genres",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "extras",
        sa.Column("_filename", sa.String(), nullable=False),
        sa.Column("_albumartist", sa.String(), nullable=False),
        sa.Column("_album", sa.String(), nullable=False),
        sa.Column("_year", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("_path", moe.core.library.lib_item.PathType(), nullable=False),
        sa.ForeignKeyConstraint(
            ["_albumartist", "_album", "_year"],
            ["albums.artist", "albums.title", "albums.year"],
        ),
        sa.PrimaryKeyConstraint(
            "_filename", "_albumartist", "_album", "_year", "_path"
        ),
        sa.UniqueConstraint("_path"),
    )
    op.create_table(
        "tracks",
        sa.Column("track_num", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("_albumartist", sa.String(), nullable=False),
        sa.Column("_album", sa.String(), nullable=False),
        sa.Column("_year", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("file_ext", sa.String(), nullable=False),
        sa.Column("path", moe.core.library.lib_item.PathType(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["_albumartist", "_album", "_year"],
            ["albums.artist", "albums.title", "albums.year"],
        ),
        sa.PrimaryKeyConstraint("track_num", "_albumartist", "_album", "_year"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "track_genres",
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("track_path", moe.core.library.lib_item.PathType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["genre"],
            ["genres.name"],
        ),
        sa.ForeignKeyConstraint(
            ["track_path"],
            ["tracks.path"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_genres")
    op.drop_table("tracks")
    op.drop_table("extras")
    op.drop_table("genres")
    op.drop_table("albums")
    # ### end Alembic commands ###
