"""custom fields.

Revision ID: 67afb7deba19
Revises: bf1e35ea8744
Create Date: 2022-09-10 20:13:59.276192

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "67afb7deba19"
down_revision = "bf1e35ea8744"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "album", sa.Column("_custom_fields", sa.JSON(none_as_null=True), nullable=True)
    )
    op.add_column(
        "extras", sa.Column("_custom_fields", sa.JSON(none_as_null=True), nullable=True)
    )
    op.add_column(
        "track", sa.Column("_custom_fields", sa.JSON(none_as_null=True), nullable=True)
    )


def downgrade():
    op.drop_column("album", "_custom_fields")
    op.drop_column("extra", "_custom_fields")
    op.drop_column("track", "_custom_fields")
    op.rename_table("extra", "extras")
