"""non-nullable fields.

Revision ID: bf1e35ea8744
Revises: 530acc53e20c
Create Date: 2022-09-10 19:27:22.352009

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bf1e35ea8744"
down_revision = "530acc53e20c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.alter_column("artist", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track", schema=None) as batch_op:
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("artist", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
