name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  github_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # TODO: add body to github release with most recent changelog additions
        # https://github.com/commitizen-tools/commitizen/issues/225
      - name: Release to GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            [Changelog](https://github.com/MoeMusic/Moe/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false

  pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
      - name: Build
        run: |
          poetry build
      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
