name: Tag Release

on:
  push:
    branches:
      - master
    paths:
      - 'CHANGELOG.rst'

jobs:
  tag_release:
    if: contains(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip commitizen

      - name: Get new tag
        run: |
          echo "tag=v$(cz version --project)" >> $GITHUB_ENV

      - name: Push new tag
        run: |
          git tag {{ env.tag }}
          git push origin {{ env.tag }}
